name: cdn-version-tree-by-tag-builder

on:
  push:
    tags:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ./
        id: publish
        with:
          git_ref: '${{ github.ref }}'
          branch: release
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
#          source_folder: .github
#          target_folder: test
#          dry_run: true
